PENDU_WORDS = [
    # Général / Rôle
    "SECOURISTE", "VICTIME", "INTERVENTION", "URGENCE", "ALERTE", "PROTECTION", "SECURITE", "EQUIPE", 
    "MATERIEL", "BILAN", "SURVEILLANCE", "TRANSMISSION", "EVACUATION", "TRANSPORT", "ASSISTANCE", 
    "SAUVETAGE", "CIVILE", "ENGAGEMENT", "SOLIDARITE", "PREVENTION",
    # Matériel
    "GANTS", "MASQUE", "OXYGENE", "DEFIBRILLATEUR", "BRANCARD", "ATTELLE", "COLLIER", "COUVERTURE", 
    "SAC", "RADIO", "LAMPE", "CISEAUX", "COMPRESSES", "PANSEMENT", "GARROT", "CANULE", 
    "INSUFFLATEUR", "ASPIRATEUR", "TENSIO", "THERMOMETRE",
    # Urgences vitales
    "ARRET", "CARDIAQUE", "HEMORRAGIE", "DETRESSE", "RESPIRATOIRE", "NEUROLOGIQUE", "CIRCULATOIRE", 
    "INCONSCIENCE", "ASPHYXIE", "OBSTRUCTION", "MALAISE", "SYNCOPE", "COMA", "NOYADE", 
    "PENDAISON", "STRANGULATION", "ETOUFFEMENT", "HYPOXIE", "CHOC", "CONVULSION",
    # Gestes
    "MASSAGE", "VENTILATION", "COMPRESSION", "DESOBSTRUCTION", "IMMOBILISATION", "RELEVAGE", 
    "BRANCARDAGE", "RETOURNEMENT", "ASPIRATION", "OXYGENATION", "REANIMATION", "PROTECTION", 
    "REFROIDISSEMENT", "RECHAUFFEMENT", "SURVEILLANCE", "EVALUATION", "OBSERVATION", "QUESTIONNEMENT", 
    "REFORMULATION", "COMMUNICATION",
    # Traumatismes
    "PLAIE", "BRULURE", "FRACTURE", "ENTORSE", "LUXATION", "TRAUMATISME", "CRANE", "THORAX", 
    "ABDOMEN", "BASSIN", "MEMBRE", "HEMATOME", "AMPUTATION", "SECTION", "CHUTE", "COLLISION", 
    "EXPLOSION", "ECRASEMENT", "PROJECTION", "IMPACT",
    # Malaises
    "ASTHME", "ALLERGIE", "ANAPHYLAXIE", "DIABETE", "HYPOGLYCEMIE", "AVC", "INFARCTUS", "FIEVRE", 
    "INFECTION", "INTOXICATION", "OVERDOSE", "DESHYDRATATION", "HYPERTHERMIE", "HYPOTHERMIE", 
    "GELURE", "COUPURE", "DOULEUR", "SPASME", "PARALYSIE", "MALAISE",
    # Relationnel
    "EMPATHIE", "CALME", "STRESS", "PANIQUE", "PEUR", "ANGOISSE", "ECOUTE", "SOUTIEN", 
    "RASSURER", "DIALOGUE", "RESPECT", "CONFIANCE", "POSTURE", "BIENVEILLANCE", "PATIENCE", 
    "HUMILITE", "AUTORITE", "LEADERSHIP", "COOPERATION", "COORDINATION",
    # Environnement
    "DANGER", "BALISAGE", "PERIMETRE", "CIRCULATION", "INCENDIE", "ELECTRICITE", "GAZ", 
    "EXPLOSION", "EFFONDREMENT", "FOULE", "RISQUE", "PROTECTION", "EVACUATION", "CONFINEMENT", 
    "SIGNALISATION", "VISIBILITE", "NUIT", "PLUIE", "FROID", "CHALEUR",
    # Bilan
    "CONSCIENCE", "RESPIRATION", "POULS", "TENSION", "SATURATION", "GLYCEMIE", "DOULEUR", 
    "PUPILLES", "PEAU", "TEMPERATURE", "FREQUENCE", "AMELIORATION", "AGGRAVATION", "STABILITE", 
    "EVOLUTION", "OBSERVATION", "NOTE", "FICHE", "RAPPORT", "COMPTE-RENDU",
    # Victimes
    "ENFANT", "NOURRISSON", "BEBE", "ADOLESCENT", "ADULTE", "SENIOR", "FEMME", "ENCEINTE", 
    "HANDICAP", "FRAGILE",
    # Organisation
    "SAMU", "POMPIERS", "POLICE", "HOPITAL", "MEDECIN", "INFIRMIER", "CHEF", "EQUIPIER", 
    "RENFORT", "REGULATION",
    # Divers
    "CASQUE", "GILET", "SIGNAL", "SIRENE", "GYROPHARE", "CIVIERE", "PLAN", "ORDRE", "PRIORITE", 
    "URGENT", "GRAVE", "LEGER", "STABLE", "CRITIQUE", "AIDE", "SOUTIEN", "ACTION", "REFLEXE", 
    "FORMATION", "ENTRAINEMENT",
    # Bonus
    "DEFIBRILLATION", "REANIMATION", "HYPERVENTILATION", "DESORIENTATION", "INCONSCIENCE", 
    "POLYTRAUMATISE", "TRAUMATISME", "INTERVENTION", "COORDINATION", "COMMUNICATION", 
    "STABILISATION", "IMMOBILISATION", "OXYGENOTHERAPIE", "SURVEILLANCE", "TRANSMISSION", 
    "SECURISATION", "EVALUATION", "ORGANISATION", "ANTICIPATION", "PREPARATION",
    # Derniers mots
    "COURAGE", "SANG-FROID", "REACTIVITE", "DISCIPLINE", "RIGUEUR", "ENGAGEMENT", "ALTRUISME", 
    "HUMANITE", "RESPECT", "RESPONSABILITE", "MISSION", "SERVICE", "ALERTER", "PROTEGER", 
    "SECOURIR", "SURVIVRE", "SAUVER", "PRESERVER", "APPRENDRE", "TRANSMETTRE",
    # 40 mots finaux
    "BENEVOLE", "FORMATION", "DIPLOME", "QUALIFICATION", "RECYCLAGE", "EXERCICE", "SIMULATION", 
    "URGENCE", "CATASTROPHE", "CRISE", "PANSEMENT", "COMPRESSIF", "HEMOSTATIQUE", "ATTENTAT", 
    "EXPLOSION", "ACCIDENT", "COLLISION", "BLESSURE", "SOINS", "SECOURS", "EQUIPE", "RADIO", 
    "APPEL", "LOCALISATION", "VICTIME", "TEMOIN", "ISOLEMENT", "CONSCIENCE", "VIGILANCE", 
    "RAPIDITE", "ORGANISATION", "PROCEDURE", "TECHNIQUE", "MANOEUVRE", "ACTION", "INTERVENTION", 
    "PRIORITE", "SAUVETAGE", "SECOURISME", "PSE"
]

# Filtering duplicates and ensuring uppercase
PENDU_WORDS = sorted(list(set([w.upper() for w in PENDU_WORDS])))
